
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: "PedidoDbPassword123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql
    networks:
      - appnet

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"      
      - "15672:15672"    
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - appnet
    restart: always

  api:
    build:
      context: backend
      dockerfile: ./Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Server=sqlserver;Database=PedidoDb;User Id=sa;Password=PedidoDbPassword123;TrustServerCertificate=True;"
      JwtSettings__SecretKey: "chave-super-secreta-123456789012345678901"
      JwtSettings__Issuer: "envio-pedidos-api"
      JwtSettings__Audience: "clientes"
      JwtSettings__ExpiresInMinutes: "60"
      RabbitMq__Host: "rabbitmq"   
      RabbitMq__Username: "guest"
      RabbitMq__Password: "guest"
    ports:
      - "5000:8080"
    depends_on:
      - sqlserver
      - rabbitmq
    networks:
      - appnet
    restart: always

  frontend:
    build:
      context: frontend  
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    depends_on:
      - api
    networks:
      - appnet
    container_name: angular-frontend
    restart: always
volumes:
  sql_data:

networks:
  appnet: