version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: "PedidoDbPassword123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql
    networks:
      - appnet
  api:
    build:
      context: backend
      dockerfile: ./Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Server=sqlserver;Database=PedidoDb;User Id=sa;Password=PedidoDbPassword123;TrustServerCertificate=True;"
    ports:
      - "5000:80"
    depends_on:
      - sqlserver
    networks:
      - appnet
    restart: always

volumes:
  sql_data:

networks:
  appnet: