version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: "SuaSenhaForte123"     
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql
    networks:
      - appnet
  api:
    build:
      context: backend
      dockerfile: ./Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Server=sqlserver;Database=MinhaAppDb;User Id=sa;Password=SuaSenhaForte123;TrustServerCertificate=True;"
    ports:
      - "5000:80"
    depends_on:
      - sqlserver
    networks:
      - appnet

volumes:
  sql_data:

networks:
  appnet: